### ISSUE TITLE
Item content only consists of subheader

### ISSUE THREAD

**Issue by leonstiegler** [taranis-ai/taranis-ai#119]
### Bug:

There are some items that only contain the article's subheader.

### Screenshots:

![ots1](https://github.com/taranis-ai/taranis-ai/assets/71084116/91a242d8-4c67-4f7c-b2c0-ff61e59e5ad1)
#### Link: https://www.ots.at/presseaussendung/OTS_20240115_OTS0046/der-guertel-ist-ein-herzstueck-der-mobilitaet-in-wien

![ots2](https://github.com/taranis-ai/taranis-ai/assets/71084116/c5eccc8a-9dc3-4ac3-bcba-8bae3fecacbe)
#### Link: https://www.ots.at/presseaussendung/OTS_20240115_OTS0086/2023-war-ein-rekordjahr-fuer-niederoesterreich-bahnen

![orf](https://github.com/taranis-ai/taranis-ai/assets/71084116/546613b7-bdc3-4247-9bce-971f0565a1f6)
#### Link: https://noe.orf.at/stories/3240665/

**Comment by b3n4kh** [comment]
This could be due to the nature of how the `RSS Collector` is trying to get the article content. Right now he is first trying to [find the content in the RSS Feed](https://github.com/taranis-ai/taranis-ai/blob/186b1c90b8e81759fd1d010b39103a288b181807/src/worker/worker/collectors/rss_collector.py#L127C1-L129C30).

Only if that fails, he gets it from the article behind the <link> tag.

The second behavior can be forced, via the "CONTENT_LOCATION", but is not documented right now, I fast track the documentation for this.

**Comment by b3n4kh** [comment]
After looking a little deeper into this very specific issue, I found that in case of OTS it wasn't the fault of Collector but rather a rendering issue in the frontend.

The issue should be fixed with the changes introduced to [CardStory.vue getDescription](https://github.com/taranis-ai/taranis-ai/commit/aaa6cdd56ddeb94e32a4d79286c5c5c99ee3f893
)

The updated documentation is however online as well: https://taranis.ai/documentation/administration/osint-sources/collectors/
