### ISSUE TITLE
Double items

### ISSUE THREAD

**Issue by leonstiegler** [taranis-ai/taranis-ai#120]
### Bug:
Some items show up/are created twice

In the first screenshot the items are exactly the same, including published date, tags, relevance and source url

In the screenshots of the second example only the published time is different

#### 29-jähriger Ukrainer:
![AWAKE TaranisAI Double items_2 2024-01-15 140418](https://github.com/taranis-ai/taranis-ai/assets/71084116/dc8a13dc-c73e-4854-a3d8-4f2ee80efc06)

#### Early Bird Registration:
![AWAKE TaranisAI Double items_3 2024-01-15 140418](https://github.com/taranis-ai/taranis-ai/assets/71084116/0e502423-a32c-433d-9947-adb859755217)

![AWAKE TaranisAI Double items_4 2024-01-15 140418](https://github.com/taranis-ai/taranis-ai/assets/71084116/75fb4780-947c-4556-8a29-9cfd09aaf2d1)

**Comment by b3n4kh** [comment]
There is one "as expected" case where this can happen, which might at least in the case of the "Early Bird" be what happened.

If an article gets "updated" as it happens with news articles its "hash" (our internal way of detecting duplicates) is different, and will be picked up again. Since the "Published Time" is different on both articles I assume this is what happened, most of the time, there just typo corrections.

The drawbacks for the alternative (overriding the existing article) are too unpredictable, so adding the article a second time seems to be the only option in this case right now. 

In case of the "29-jähriger Ukrainer" timestamps seem to match. @leonstiegler could you share the URL to the articles, I will take a look and try to reproduce this.

**Comment by leonstiegler** [comment]
Thanks for the explanation!

Here are the links to the articles:

[Early Bird](https://connect.geant.org/2024/01/15/early-bird-registration-is-now-open-for-tnc24#:~:text=Early%20bird%20registration%20is%20open,Visit%20the%20TNC24%20website.)

[29-jähriger Ukrainer](https://www.heise.de/news/29-jaehriger-Ukrainer-als-Drahtzieher-hinter-Kryptomining-Kampagne-verhaftet-9597362.html)

After searching for the "29-jähriger Ukrainer" article in our TaranisAI instance I found 2 additional before unseen items.

The article headline seems to be changed now, after your explanation it would make sense to have multiple items for the same article. 
Although 4 items are a bit strange especially if all of the changes needed to happened and got pulled in the same minute (I checked, and all the links lead to the same URL.).
The tags on them are also strange; items with the same headline have different tags, but each item has a corresponding item with the same tags but a different headline.

![29](https://github.com/taranis-ai/taranis-ai/assets/71084116/702ab452-d61a-4858-95c5-7360d689e0c1)

**Comment by b3n4kh** [comment]
I looked at our heise articles and found double articles as well, it turned out that we have two differnt heise RSS feed that sometimes publish the same article:

![image](https://github.com/taranis-ai/taranis-ai/assets/6696618/ee0aa85a-17ba-4be0-9c7b-00ea9fd17249)
![image](https://github.com/taranis-ai/taranis-ai/assets/6696618/b56b2398-a913-4a82-be62-25e332b2b6c9)

![image](https://github.com/taranis-ai/taranis-ai/assets/6696618/261977b3-c1c3-497c-ab96-abcac7ae1888)



As for the geant Early Bird, I opend their feed and they actually published the artcile twice, it is still live in their feed right now:

![image](https://github.com/taranis-ai/taranis-ai/assets/6696618/ca34d4f7-de3d-46ff-ad99-03fcdd0b6fd4)
