### ISSUE TITLE
RSSCollector object has no attribute

### ISSUE THREAD

**Issue by ikumi-11** [taranis-ai/taranis-ai#126]
When I key in RSS feed then click on Click Sources, this problem will occur.

![image](https://github.com/taranis-ai/taranis-ai/assets/82429415/d73afec2-b957-4d35-800d-741844fc47ed)
![image](https://github.com/taranis-ai/taranis-ai/assets/82429415/395017c0-d217-4ea1-b782-4d9edca1e5af)

Even if I tried using your provided RSS feed, the problem still occur.
![image](https://github.com/taranis-ai/taranis-ai/assets/82429415/4e5cc632-ad83-4ef4-8047-e3236c2c8778)

**Comment by b3n4kh** [comment]
Hi That is an issue introduced by the introduction of: https://github.com/taranis-ai/taranis-ai/blob/4ae0d8f664b7d994edf1a2503885312fed6612c2/src/worker/worker/collectors/base_web_collector.py

But should hopefully be fixed with: https://github.com/taranis-ai/taranis-ai/commit/5af54c6b5b26038995abc8bf1d6b677e9b47fdea

**Comment by not4Pedro** [comment]
Is this still relevant? @b3n4kh
