### ISSUE TITLE
Refactor ForeignKey on delete behavior 

### ISSUE THREAD

**Issue by b3n4kh** [taranis-ai/taranis-ai#26]
From Taranis-NG created by [ewoiset](https://github.com/ewoiset): ait-cs-IaaS/Taranis-NG#136  

- [ ] Refactor on delete behavior -> cascade, set null, default (error)
- [ ] handle error message when on delete throws error 
- [ ] check all foreign keys

related issue: https://github.com/ait-cs-IaaS/Taranis-NG/issues/117

![Image](https://github.com/ait-cs-IaaS/Taranis-NG/assets/88492381/65f59246-5e83-4769-b344-3cb026707bd2)

**Comment by ewoiset** [comment]
![Image](https://github.com/taranis-ai/taranis-ai/assets/88492381/a421a9e1-6b56-4c72-9711-f6b691825e2e)

**Comment by ewoiset** [comment]
- NewsItemAggregateNewsItemAttribute no need to change as it is solved via relationship.secondary
-

**Comment by ewoiset** [comment]
no changes where made with: 
- news_item_aggregate because it was unclear what happens with news_item. currently news items are delete when the aggregate only has one item. However, when there are multiple items, in an aggregate, all are deleted but the item with the same id as the aggregate 
- parameter_value as this was wrongly marked

**Comment by b3n4kh** [comment]
Fixed this issue with: https://github.com/taranis-ai/taranis-ai/pull/209
