### ISSUE TITLE
Add generic HTTP header feature to RSS collector

### ISSUE THREAD

**Issue by jfstenuit** [taranis-ai/taranis-ai#293]
Sometimes, RSS feeds are only available with very specific pattern of HTTP headers.

Changing the User-Agent help solve the issue in most of the cases, but sometime, specific extra HTTP headers need to be supplied : 

- Specific cookie
- Bearer token
- Accepted payload (f.i. Accept: application/json)
- ...

With the ability to tweak the HTTP headers, we can address most of those issues.

**Comment by b3n4kh** [comment]
There should be a method to [base_web_collector.py](https://github.com/taranis-ai/taranis-ai/blob/00e2b869b89eda5e23b241bd902a22e88ad09948/src/worker/worker/collectors/base_web_collector.py#L24) that extends the `self.headers` based on a source parameter called `ADDITIONAL_HEADERS`.

This would require to also update the rt_collector to use this new method instead of the current `set_headers` since this would override the headers otherwise.

**Comment by not4Pedro** [comment]
related #302

**Comment by not4Pedro** [comment]
resolved with #304
