### ISSUE TITLE
API: Assess: Create News-Item silently fails - Returns ID of new news item but cannot access item under id

### ISSUE THREAD

**Issue by SaltySolomon** [taranis-ai/taranis-ai#331]
Like the title says, I am currently testing the API in order to create some tooling and when I try to create a news item I get an ID back but then I cannot access the news item either via the API or the GUI.

**Comment by not4Pedro** [comment]
As for the creation of NewsItems, you should use the `"source": "manual"`. Otherwise, you need to make sure you have the sources properly imported/created among OsintSources.

Something like this:
```
$ curl -X POST http://<domain>:5000/api/assess/news-items \   
-H "Authorization: Bearer <bearer>" \
-H "Content-Type: application/json" \
-d '{
  "title": "test manual 2",
  "review": "",
  "content": "",
  "link": "",
  "source": "manual",
  "osint_source_id": "manual",
  "author": "Arthur Dent",
  "published": "2024-09-02T16:20:20.574Z",
  "collected": "2024-09-02T16:20:37.993Z",
  "attributes": []
}'
```
Response:
```
{
  "id": "fd7625ce-1084-49fc-8f18-48cb3589158c",
  "message": "success"
}
```
Working with the last commit, the item is accessible in the GUI.

As for getting the NewsItem, it is a bit more tricky. When a NewsItem is created with the endpoint `/api/assess/news-items`, the returned `id` is not the NewsItem's `id`, but the Story's `id` (which is another representation), that's why it returns "not found" if you query the endpoint `api/assess/news-items/fd7625ce-1084-49fc-8f18-48cb3589158c`


Then we can query by the Story `id` that was returned like this.

$ curl -X GET http://<domain>:5000/api/assess/story/fd7625ce-1084-49fc-8f18-48cb3589158c \  
-H "Authorization: Bearer <bearer>"
{
  "comments": "",
  "created": "2024-09-02T16:20:20.574000",
  "description": "",
  "dislikes": 0,
  "id": "fd7625ce-1084-49fc-8f18-48cb3589158c",
  "important": false,
  "likes": 0,
  "links": [],
  "news_items": [
    {
      "author": "Arthur Dent",
      "collected": "2024-09-02T16:20:37.993000",
      "content": "",
      "hash": "08127a53d53c1f619a2f82af451d0e8059ab4060de53e4a1291b047719a16094",
      "id": "6fa4a5b4-ae30-49ba-b4de-d6b771f04b92",
      "language": "",
      "link": "",
      "osint_source_id": "manual",
      "published": "2024-09-02T16:20:20.574000",
      "review": "",
      "source": "manual",
      "story_id": "fd7625ce-1084-49fc-8f18-48cb3589158c",
      "title": "test manual 2",
      "updated": "2024-09-02T15:35:46.595869"
    }
  ],
  "read": false,
  "relevance": 0,
  "summary": "",
  "tags": [],
  "title": "test manual 2",
  "updated": "2024-09-02T18:24:59.628207"
}


When we look at how the `id`s are assigned, in my test case, the actual NewsItem's `id` is `6fa4a5b4-ae30-49ba-b4de-d6b771f04b92`, therefore, I can do following:
```
$ curl -X GET http://<domain>:5000/api/assess/news-items/6fa4a5b4-ae30-49ba-b4de-d6b771f04b92 \
-H "Authorization: Bearer <bearer>"
{
  "author": "Arthur Dent",
  "collected": "2024-09-02T16:20:37.993000",
  "content": "",
  "hash": "08127a53d53c1f619a2f82af451d0e8059ab4060de53e4a1291b047719a16094",
  "id": "6fa4a5b4-ae30-49ba-b4de-d6b771f04b92",
  "language": "",
  "link": "",
  "osint_source_id": "manual",
  "published": "2024-09-02T16:20:20.574000",
  "review": "",
  "source": "manual",
  "story_id": "fd7625ce-1084-49fc-8f18-48cb3589158c",
  "title": "test manual 2",
  "updated": "2024-09-02T15:35:46.595869"
}

```

I feel like, we should maybe document this behaviour better.

**Comment by b3n4kh** [comment]
We should probably just return both, news_item_id and the story_id

**Comment by not4Pedro** [comment]
@b3n4kh Yes, we shoud consider that, maybe starting with returning `story_id`, instead of just `id`. 

But there is still an issue, if you create an item without the `osint_source_id: manual`, the Story gets to the database, but is not accessible from the GUI, only by API.

**Comment by SaltySolomon** [comment]
Yeah, returning both news_item_id and story_id would be a usefull return that can be worked with without additional calls.

Regarding the behavior of the osint_source_id topic. Documenting the behaviour would be a good first step. The "clean" sollution would be to a. change it to an optional field with the default being manual and b. adding a check that its actually in any of the existing sources.
